name: mlmsdft
channels:
  - nodefaults
  - conda-forge
dependencies:
  # scipy cannot be installed via pip, because of a bug (missing openblas dependency)
  - scipy==1.14.1
  - pip
  - pip:
    - becke-multicenter-integration==0.0.2
    - coverage==7.9.1
    - jsonargparse[signatures]==4.32.1
    - matplotlib==3.9.2
    - numpy==2.1.1
    - opt-einsum==3.4.0
    - pandas==2.3.1
    - prefect==3.6.20
    - pyscf==2.9.0
    - ruff==0.12.1
    - torch==2.7.1
    - git+https://github.com/humeniuka/multistate_density_functionals
