#!/usr/bin/env python
# coding: utf-8
import becke
import numpy
import pyscf.dft
import pyscf.gto
import torch
from torch import Size
from torch.autograd import gradcheck
from tqdm import tqdm
import unittest

from mlmsdft.dft.density import MultistateMatrixDensity
from mlmsdft.dft.density import MultistateMatrixDensityCAS
from mlmsdft.dft.density import MultistateMatrixDensityKohnSham
from mlmsdft.dft import hartree

from dft.fixture import FixtureMixin
from nn.test_functional import random_tensor


class HartreeFunctionalPoisson:
    def __init__(self, mol: pyscf.gto.Mole, level=8):
        """
        For testing purposes only.

        NOTE: :class:`~.HartreeFunctionalPoisson` is much slower than :class:`~.HartreeFunctionalAO`
            because the Poisson equation is solved numerically on a grid.

        :param mol: The molecule defines the integration grid.
        :type mol: pyscf.gto.Mole

        :param level: The level (3-8) controls the number of grid points
           in the integration grid.
        :type level: int
        """
        # generate a multicenter integration grid
        self.grids = pyscf.dft.gen_grid.Grids(mol)
        self.grids.level = level
        self.grids.build()

    def __call__(
            self,
            msmd : MultistateMatrixDensity):
        """
        compute the Hartree-like part of the electron-electron repulsion operator
        in the subspace of electronic states,

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫∫' Dᵢₖ(r) Dₖⱼ(r')/|r-r'|

        where Dᵢⱼ(r) is the electronic density of the state Ψᵢ, Dᵢᵢ(r) = ρᵢ(r),
        or the transition density between the states Ψᵢ and Ψⱼ, Dᵢⱼ(r).

        The 6-dimensional integral is calculated by solving the Poisson equation
        for the electrostatic potential generated by one of the (transition) densities,

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫ Dᵢₖ(r) Vₖⱼ(r)

        where

          ∇²Vₖⱼ(r) = -4π Dₖⱼ(r)

        is solved on a multicenter Becke grid.

        :param msmd: The multistate matrix density in the electronic subspace
        :type msmd: :class:`~.MultistateMatrixDensity`

        :return hartree_like_matrix: The Hartree-like matrix Jᵢⱼ in the subspace
           of the electronic states i,j=1,...,nstate
        :rtype hartree_like_matrix: numpy.ndarray of shape (nstate,nstate)
        """
        # number of grid points
        ncoord = self.grids.coords.shape[0]
        # number of electronic states in the subspace
        nstate = msmd.number_of_states

        # Evaluate D(r) on the integration grid.
        D, _, _ = msmd.evaluate(self.grids.coords)
        # sum over spins
        D = torch.einsum('ss...->...', D)

        # For solving the Poisson equation another multicenter Becke grid
        # is employed, which can have a different number of angular and radial
        # grid points than the one for doing the integrals.

        # The multicenter grid is defined by the centers ...
        atomlist = []
        for nuclear_charge, nuclear_coords in zip(
                msmd.mol.atom_charges(), msmd.mol.atom_coords()):
            atomlist.append((int(nuclear_charge), nuclear_coords))
        # ... and the radial and angular grids.
        becke.settings.radial_grid_factor = 3
        becke.settings.lebedev_order = 23

        # [1] The Poisson equation is solved for each Dₖⱼ(r).
        V = numpy.zeros((ncoord,nstate,nstate))
        for k in range(0, nstate):
            for j in range(0, nstate):
                # A function for evaluating the (transition) density Dₖⱼ(r) on
                # the multicenter Becke grid.
                def density_function(x, y, z):
                    # The `becke` module and the `mlmsdft` module use different
                    # shapes for the coordinates of the grid points. Before
                    # passing the grid to `mlmsdft`, the arrays have to be flattened
                    # and reshaped as (ncoord,3). Before returning the density,
                    # it has to be brought into the same shape as each input coordinate
                    # array.
                    coords = numpy.vstack(
                        [x.flatten(), y.flatten(), z.flatten()]).transpose()

                    # Evaluate the matrix density.
                    D, _, _ = msmd.evaluate(coords)
                    # sum over spins
                    D = torch.einsum('ss...->...', D)

                    # Take the (k,j) block with (transition) density
                    # and convert it to numpy array.
                    density = D[:,k,j].numpy()

                    # Give it the same shape as the input arrays.
                    density = numpy.reshape(density, x.shape)
                    return density

                # The solution of the Poisson equation
                #  ∇²potential(r) = -4π density(r)
                # is returned as a callable.
                potential_function = becke.poisson(atomlist, density_function)

                # The electrostatic potential is evaluated on the same
                # integration grid as the density.
                V[:,k,j] = potential_function(
                    # x
                    self.grids.coords[:,0],
                    # y
                    self.grids.coords[:,1],
                    # z
                    self.grids.coords[:,2])

        # [2] Integrate and do the matrix-matrix product.
        #
        #  J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫ Dᵢₖ(r) Vₖⱼ(r)
        #
        hartree_like_matrix = 0.5 * numpy.einsum(
            'r,rik,rkj->ij',
            self.grids.weights,
            D, V)

        return hartree_like_matrix


class TestHartreeFunctionalAO(unittest.TestCase, FixtureMixin):
    def check_hartree_matrix(self, msmd):
        """
        The Hartree-like energy is calculated in two different ways:
         1) By solving the Poisson equation for each (transition) density and
            integrating the product of the resulting electrostatic potential
            V(r) with the matrix density D(r) numerically on a grid
         2) By contracting the electronic repulsion integrals (ab|cd) in the
            AO basis with the AO (transition) density matrices (exact).

        :param msmd: The multistate matrix density in the electronic subspace
        :type msmd: :class:`~.MultistateMatrixDensity`
        """
        # The exact potential energy matrix is calculated by contracting the
        # (transition) density matrices in the AO basis with the electron
        # repulsion integrals.
        # representation of matrix density in AO basis summed over spins,
        # Dᵦᵧᵢⱼ = Dᵅᵅᵦᵧᵢⱼ + Dᵝᵝᵦᵧᵢⱼ
        density_matrices_ao = torch.einsum(
            'ss...->...',
            msmd.density_matrices_ao()
        )
        # compute Hartree matrix J[D(r)]ᵢⱼ
        hartree_functional = hartree.HartreeFunctionalAO(msmd.mol)
        J = hartree_functional(density_matrices_ao)

        # Evaluate J[D(r)] by solving the Poisson equation and integration on the grid.
        # functional for Hartree-like energy J[D(r)]
        hartree_like_functional = HartreeFunctionalPoisson(msmd.mol)
        J_ref = hartree_like_functional(msmd)
        # Convert to Torch tensor.
        J_ref = torch.from_numpy(J_ref).to(dtype=J.dtype, device=J.device)

        torch.testing.assert_close(J, J_ref, atol=1.0e-4, rtol=1.0e-4)

        # The diagonal elements of the Hartree matrix should be all positive.
        self.assertTrue(torch.all(torch.diag(J) >= 0.0))

    def test_hartree_matrix(self):
        """
        Compare Hartree term J[D(r)] from numerical integration with exact matrix elements.
        """
        for name, mol in tqdm(
                # Only for finite systems can the Coulomb energy be calculated by
                # using Becke's multicenter grids, so the tests only work for molecules,
                # but not crystals.
                self.create_test_molecules_minimal().items()):
            for msmd in self.create_random_matrix_densities(mol):
                with self.subTest(
                    molecule=name,
                    msmd=msmd.__class__.__name__,
                    density_params="random"
                ):
                    with torch.no_grad():
                        self.check_hartree_matrix(msmd)

    def check_autograd_kohn_sham(self, mol):
        """
        Compare analytical and numerical gradients of Hartree matrix J[D(r)]ᵢⱼ
        with respect to orbital rotations.
        """
        hartree_functional = hartree.HartreeFunctionalAO(mol)

        msmd_0 = MultistateMatrixDensityKohnSham.from_guess(mol, guess="random")
        orbital_coefficients = msmd_0.orbital_coefficients()

        def wrapper_function(orbital_rotation_params):
            msmd = MultistateMatrixDensityKohnSham(
                mol, orbital_coefficients, orbital_rotation_params
            )
            # representation of matrix density in AO basis summed over spins,
            # Dᵦᵧᵢⱼ = Dᵅᵅᵦᵧᵢⱼ + Dᵝᵝᵦᵧᵢⱼ
            density_matrices_ao = torch.einsum(
                'ss...->...',
                msmd.density_matrices_ao()
            )
            # compute Hartree matrix J[D(r)]ᵢⱼ
            outputs = hartree_functional(density_matrices_ao)
            return outputs

        nao, nmo = orbital_coefficients.size()
        # Random orbital rotation parameters.
        nrot = (nmo*(nmo-1))//2
        orbital_rotation_params = random_tensor(Size([nrot]))
        orbital_rotation_params.requires_grad_(True)

        # Compare analytical gradients computed by backpropagation
        # finite difference approximation.
        inputs = (orbital_rotation_params,)
        gradcheck(wrapper_function, inputs)

    def test_autograd_kohn_sham(self):
        """
        Check that automatic differentiation works for D(X;r) w/r/t X.
        """
        for name, mol in tqdm(self.create_test_systems_minimal().items()):
            with self.subTest(molecule=name):
                self.check_autograd_kohn_sham(mol)

    def check_autograd_cas(self, mol):
        """
        Compare analytical and numerical gradients of the Hartree-like
        matrix J[D(r)]ᵢⱼ with respect to orbital and state rotation parameters of
        a CAS matrix density (multiple state).
        """
        hartree_functional = hartree.HartreeFunctionalAO(mol)

        # CAS: 2 electrons in 2 orbitals
        norb = 2
        nelec = min(2, sum(mol.nelec))
        msmd_0 = MultistateMatrixDensityCAS.from_guess(mol, norb, nelec, guess="random")
        orbital_coefficients = msmd_0.orbital_coefficients()
        state_coefficients = msmd_0.state_coefficients()

        def wrapper_function(orbital_rotation_params, state_rotation_params):
            msmd = MultistateMatrixDensityCAS(
                mol, norb, nelec,
                orbital_coefficients, orbital_rotation_params,
                state_coefficients, state_rotation_params
            )
            # representation of matrix density in AO basis summed over spins,
            # Dᵦᵧᵢⱼ = Dᵅᵅᵦᵧᵢⱼ + Dᵝᵝᵦᵧᵢⱼ
            density_matrices_ao = torch.einsum(
                'ss...->...',
                msmd.density_matrices_ao()
            )
            # compute Hartree-like matrix J[D(r)]ᵢⱼ
            outputs = hartree_functional(density_matrices_ao)
            return outputs

        nao, nmo = orbital_coefficients.size()
        # Random orbital rotation parameters.
        nrot = (nmo*(nmo-1))//2
        orbital_rotation_params = random_tensor(Size([nrot]))
        orbital_rotation_params.requires_grad_(True)

        # Random state rotation parameters.
        nstate = msmd_0.number_of_states
        nrot_ci = (nstate*(nstate-1))//2
        state_rotation_params = random_tensor(Size([nrot_ci]))
        state_rotation_params.requires_grad_(True)

        # Compare analytical gradients computed by backpropagation
        # finite difference approximation.
        inputs = (orbital_rotation_params, state_rotation_params)
        gradcheck(wrapper_function, inputs)

    def test_autograd_cas(self):
        """
        Check that automatic differentiation works for D(r) w/r/t orbital
        and state rotation parameters.
        """
        for name, mol in tqdm(self.create_test_molecules_minimal().items()):
            with self.subTest(molecule=name):
                self.check_autograd_cas(mol)


if __name__ == "__main__":
    unittest.main()
